### PR TITLE
Update Testing Info in README

### PR DESCRIPTION
**Pull request by timmyc**
Few minor updates to the README with more current testing instructions.

### CODE REVIEW

**Comment by nylen** [comment]
This is a good idea, I wasn't sure how to run the tests before.

Why wouldn't we just provide `test/fixture.json` so that the tests run out of the box?

Also, when I run `make test-all` in this branch, I get a test failure:

```
  1) apiVersion should request changing api version:
     Uncaught Error: Bad Request
      at Request.callback (/Users/james/a8c/code/wpcom.js/node_modules/wpcom-xhr-request/node_modules/superagent/lib/node/index.js:785:17)
      at IncomingMessage.<anonymous> (/Users/james/a8c/code/wpcom.js/node_modules/wpcom-xhr-request/node_modules/superagent/lib/node/index.js:983:12)
      at IncomingMessage.emit (events.js:129:20)
      at _stream_readable.js:908:16
      at process._tickCallback (node.js:355:11)
```

**Comment by timmyc** [comment]
I think the idea is the fixture file should be populated with your own dummy data.  If you look at the old version in the diff you can see it is just all <insert something here>.

@retrofox sent me his file and I did strip out his testing site url and global token... so just pushed up another change to the README about changing out those two values to run the test suite.

I was wondering though about having tests that don't hit the live api.  In calypso I have some mock responses that I return to test out parsing of payloads.

**Comment by nylen** [comment]
Agreed.  It would be good to mock out API responses, I haven't used these modules but they look promising:

- [uber/eight-track](https://github.com/uber/eight-track)
- [twolfson/nine-track](https://github.com/twolfson/nine-track)

**Comment by nylen** [comment]
Since this is an improvement I vote to merge it as-is, knowing that we want to clean up the tests later.  I'll do this tomorrow if no one objects or beats me to it.  I'll also try to get to mocking up the test requests sometime in the next few weeks.

**Pull request merged**
