### PR TITLE
Update to Babel 6

### PR DESCRIPTION
**Pull request by TooTallNate**
- Update to Babel 6, uses `babel-runtime` v6.9.2 as a dependency.
- Removes the `dist` dir; compiled files should not be committed to the repo; it should happen prepublish time
- There is now a `prepublish` npm hook to run `make build`
- Update "wpcom-proxy-request" to v2 because it was outdated as well (only a dev dependency)

@retrofox I might have not set up the tests properly so I might need your help with that part.

### CODE REVIEW

**Comment by TooTallNate** [comment]
The tests are working locally for me at this point.

I'm not sure why circleci is failing… I think it's related to their cache, because it shouldn't be installing babel v5 at this point. If you now of a way to clear the cache, then we should try that.

**Comment by aduth** [comment]
Looks to be passing after a rebuild without cache @TooTallNate ! 😄

**Comment by TooTallNate** [comment]
Lol, not quite... Looks like [Open Babel](http://openbabel.org/wiki/Main_Page) is getting in the way of the build system now. Taking a look.

**Comment by retrofox** [comment]
we've had some issues using hooks before. I remember tried using `publish`, `prepublish`, ... and in that moment we decided keep this folder under control. But actually we could remove `dist/` folder from here and keep it into npm package. I personally prefer this way.

**Comment by retrofox** [comment]
LGTM. I think we should create a npm beta version before to the new one. It allows us test the right integration in the npm publish process.

**Comment by TooTallNate** [comment]
Ok, CircleCI is [looking good now](https://circleci.com/gh/Automattic/wpcom.js/430). Merging.

**Pull request merged**
