### PR TITLE
Fix jsdoc etc. to support static+runtime analysis

### PR DESCRIPTION
**Pull request by nylen**
For Team I/O's current meetup project we're beefing up the developer site, including generating sample API requests.  I'm doing some static+runtime analysis of wpcom.js to auto-generate the code for these requests.  These are jsdoc and other changes needed to support that work.

### CODE REVIEW

**Comment by jkudish** [comment]
:+1:

**Comment by nylen** [comment]
Not ready for merge yet.  There are 2 ways to get to the endpoint `/sites/SITE_ID/posts/POST_ID/replies/` which is confusing:

```js
wpcom('<token>')
    .site(id)
    .post(id)
    .comment([cid])
    .replies([query], fn);

wpcom('<token>')
    .site(id)
    .post(id)
    .comments([query], id);
```

To fix this, `Comment#replies` needs to move to the `Post` class, which will remove the need for commit 26c7bc8.

**Comment by nylen** [comment]
... and that `.comments(id)` doesn't look right either

**Comment by retrofox** [comment]
You're right about there are two ways to get the comments of a post.
First one corresponds to esencial structure that wpcom.js has.

```js
wpcom('<token>')
    .site(id)
    .post(id)
    .comment([cid])
    .replies([query], fn);
```

And the second one is an additional method that attempts make the api a bit more friendly. So if you wanna get comments of post just make
```js
wpcom('<token>')
    .site(id)
    .post(id)
    .comments([query], fn);
```
It isn't the only one method that is in some way duplicated.

**Comment by nylen** [comment]
I've mapped out the tree of possible `wpcom.js` method calls and which API endpoints they call.  First we will use this to automatically generate `wpcom.js` code examples for https://developer.wordpress.com/.  In the future it will be a good way to provide automated code checks:  I am doing some testing for consistency between the JSDoc and the code now, and I plan to add more in a few hours.

Here is the [code](https://github.com/Automattic/wpcom.js-samples) and the [example output](https://gist.github.com/nylen/33de7ef403dd32b8d082) so far.  I include methods as "reachable" in the call tree if they have either:

- a JSDoc `@api public` tag
- a `_publicAPI` property

Without the `_publicAPI` property I cannot map any of these 25 methods, since they are all added to the `Site` class at runtime:

```
call Site#categoriesList [ {}, [Function] ] [ 'WPCOM#site', 'Site#categoriesList' ]
call Site#commentsList [ {}, [Function] ] [ 'WPCOM#site', 'Site#commentsList' ]
call Site#followsList [ {}, [Function] ] [ 'WPCOM#site', 'Site#followsList' ]
call Site#mediaList [ {}, [Function] ] [ 'WPCOM#site', 'Site#mediaList' ]
call Site#postsList [ {}, [Function] ] [ 'WPCOM#site', 'Site#postsList' ]
call Site#shortcodesList [ {}, [Function] ] [ 'WPCOM#site', 'Site#shortcodesList' ]
call Site#embedsList [ {}, [Function] ] [ 'WPCOM#site', 'Site#embedsList' ]
call Site#stats [ {}, [Function] ] [ 'WPCOM#site', 'Site#stats' ]
call Site#statsClicks [ {}, [Function] ] [ 'WPCOM#site', 'Site#statsClicks' ]
call Site#statsComments [ {}, [Function] ] [ 'WPCOM#site', 'Site#statsComments' ]
call Site#statsCommentFollowers [ {}, [Function] ] [ 'WPCOM#site', 'Site#statsCommentFollowers' ]
call Site#statsCountryViews [ {}, [Function] ] [ 'WPCOM#site', 'Site#statsCountryViews' ]
call Site#statsFollowers [ {}, [Function] ] [ 'WPCOM#site', 'Site#statsFollowers' ]
call Site#statsPublicize [ {}, [Function] ] [ 'WPCOM#site', 'Site#statsPublicize' ]
call Site#statsReferrers [ {}, [Function] ] [ 'WPCOM#site', 'Site#statsReferrers' ]
call Site#statsSearchTerms [ {}, [Function] ] [ 'WPCOM#site', 'Site#statsSearchTerms' ]
call Site#statsStreak [ {}, [Function] ] [ 'WPCOM#site', 'Site#statsStreak' ]
call Site#statsSummary [ {}, [Function] ] [ 'WPCOM#site', 'Site#statsSummary' ]
call Site#statsTags [ {}, [Function] ] [ 'WPCOM#site', 'Site#statsTags' ]
call Site#statsTopAuthors [ {}, [Function] ] [ 'WPCOM#site', 'Site#statsTopAuthors' ]
call Site#statsTopPosts [ {}, [Function] ] [ 'WPCOM#site', 'Site#statsTopPosts' ]
call Site#statsVideoPlays [ {}, [Function] ] [ 'WPCOM#site', 'Site#statsVideoPlays' ]
call Site#statsVisits [ {}, [Function] ] [ 'WPCOM#site', 'Site#statsVisits' ]
call Site#tagsList [ {}, [Function] ] [ 'WPCOM#site', 'Site#tagsList' ]
call Site#usersList [ {}, [Function] ] [ 'WPCOM#site', 'Site#usersList' ]
```

`replies` is the only method I found that has two different possible call paths to hit the same API endpoint (I am not including aliases like `cat = category`).  If I am missing other methods that are duplicated in a different way, please give me an example.

I still need the fix in 26c7bc8 for now but let's discuss moving `replies` to `Post` at #94 since it's really a separate change.

**Comment by retrofox** [comment]
@nylen correct me If I wrong but the property `_publicAPI` will be exposed in these methods, right ? I don't think it's a good idea.

**Comment by jkudish** [comment]
Have any alternate suggestions @retrofox ?

**Comment by retrofox** [comment]
@nylen how are you getting the wpcom.js methods to build the examples ? Can you walk through of an instance of WPCOM ?

**Comment by nylen** [comment]
I'm already doing that.  I explained it in [a comment above](https://github.com/Automattic/wpcom.js/pull/92#issuecomment-94454898) and linked to the code.

**Comment by retrofox** [comment]
@nylen are you using introspection ? can you paste here where and how are you reading the methods ?.

**Comment by retrofox** [comment]
> Without the _publicAPI property I cannot map any of these 25 methods, since they are all added to the Site class at runtime:

I mean maybe you could create an instance of `WPCOM`, then `SITE` instance.

you can reproduce this list in www.wpcomjs.com.

```js
var site = wpcom.site('blog.wordpress.com');
// inspect site.__proto__
```

**Comment by nylen** [comment]
As we discussed internally, what you propose is already what I am doing. However, I cannot loop over all methods because there are some that are private and should not be called automatically, for example `WPCOM#sendRequest`.  This is why I need a flag to mark methods which are "safe" or "public".

Here is the larger picture of what this change will allow us to do:

- Promote this library publicly on https://developer.wordpress.com/
- Automatically verify consistency between JSDoc and code (it is how I found many of the issues in this PR)
- Add a build and continuous integration process to this library
  - Verify that all API endpoints used by this library are valid
  - Automatically list all API endpoints that are not covered by this library
- Automatically generate the documentation for this library based on https://public-api.wordpress.com/rest/v1.1/help (try it with `Accept: application/json` header, it's a nice source of data about our API!)

I do not understand your concern with adding a property that users will never see, especially when it enables so many possibilities for the future.  I am surprised that there was this much discussion on what I thought was a simple and unobtrusive change.

If we can find a better approach later, then that is a wonderful thing, but our team meetup is almost over.  I need to merge these changes and do a release so that we can deploy a minimum viable product.

**Comment by timmyc** [comment]
looks fine to me :shipit:

**Comment by retrofox** [comment]
thanks a lot @nylen.

**Pull request merged**
