### PR TITLE
Update Taxonomies

### PR DESCRIPTION
**Pull request by timmyc**
Applying some updates per feedback from @aduth.

To test: `make test wpcom.site.taxonomy`

### CODE REVIEW

**Comment by aduth** [comment]
`dist/lib/batch.js` changes are unexpected, but maybe just hadn't been regenerated since a recent change?

What did you think about [this suggestion](https://github.com/Automattic/wpcom.js/pull/177/files#r59564228)?

Otherwise, looking good to me :+1:

**Comment by timmyc** [comment]
> dist/lib/batch.js changes are unexpected, but maybe just hadn't been regenerated since a recent change?

I'm not too certain about that but am guessing it was generated when I ran the test suite.  Perhaps @retrofox could give some insight there.

Let me update the tests too.

**Comment by retrofox** [comment]
> I'm not too certain about that but am guessing it was generated when I ran the test suite. Perhaps @retrofox could give some insight there.

Yes, I merged a PR which but I didn't update the dist/ folder. It was my mistake.

I wonder if we should commit changes in the base code and the compiled files in the same PR.
Maybe we should update the compiled files ( `./dist` folder ) just before that a new release is created and the npm package is published.

**Comment by retrofox** [comment]
@timmyc We can't use ES6 for test ATM. The reason is because the way to compiles the testing web app is awful. I use a lot this testing page when I use `calypso.localhost` host over a browser.

image

I'm aware that we have to work in this testing page.

**Comment by timmyc** [comment]
@retrofox I removed the test changes from this branch, sorry about that.

**Comment by retrofox** [comment]
:+1: :ship:

**Pull request merged**
